Table_EquipFake = {
  [25177] = {
    id = 25177,
    GroupID = 29020,
    Type = "Mount",
    EquipType = 12,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [25178] = {
    id = 25178,
    GroupID = 29020,
    Type = "Mount",
    EquipType = 12,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [25179] = {
    id = 25179,
    GroupID = 29020,
    Type = "Mount",
    EquipType = 12,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [25180] = {
    id = 25180,
    GroupID = 29020,
    Type = "Mount",
    EquipType = 12,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [25181] = {
    id = 25181,
    GroupID = 29021,
    Type = "Mount",
    EquipType = 12,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [25182] = {
    id = 25182,
    GroupID = 29021,
    Type = "Mount",
    EquipType = 12,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [25183] = {
    id = 25183,
    GroupID = 29021,
    Type = "Mount",
    EquipType = 12,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [25184] = {
    id = 25184,
    GroupID = 29021,
    Type = "Mount",
    EquipType = 12,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [500164] = {
    id = 500164,
    Type = "mouth",
    EquipType = 6,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [500165] = {
    id = 500165,
    Type = "Wing",
    EquipType = 9,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [500166] = {
    id = 500166,
    Type = "wing",
    EquipType = 9,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [500167] = {
    id = 500167,
    Type = "Wing",
    EquipType = 9,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [500168] = {
    id = 500168,
    Type = "Wing",
    EquipType = 9,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [500169] = {
    id = 500169,
    Type = "Wing",
    EquipType = 9,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [500170] = {
    id = 500170,
    Type = "Wing",
    EquipType = 9,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [500171] = {
    id = 500171,
    Type = "Wing",
    EquipType = 9,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [500172] = {
    id = 500172,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600051] = {
    id = 600051,
    Type = "Mouth",
    EquipType = 13,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 147
  },
  [600052] = {
    id = 600052,
    Type = "Mouth",
    EquipType = 13,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 139
  },
  [600053] = {
    id = 600053,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 311
  },
  [600054] = {
    id = 600054,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 239
  },
  [600055] = {
    id = 600055,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 341
  },
  [600056] = {
    id = 600056,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 343
  },
  [600057] = {
    id = 600057,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 256
  },
  [600058] = {
    id = 600058,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600059] = {
    id = 600059,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 239
  },
  [600060] = {
    id = 600060,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 239
  },
  [600061] = {
    id = 600061,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 222
  },
  [600062] = {
    id = 600062,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 257
  },
  [600063] = {
    id = 600063,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 324
  },
  [600064] = {
    id = 600064,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600065] = {
    id = 600065,
    GroupID = 45893,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600066] = {
    id = 600066,
    GroupID = 45893,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600067] = {
    id = 600067,
    GroupID = 45877,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600068] = {
    id = 600068,
    GroupID = 45877,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600069] = {
    id = 600069,
    GroupID = 45877,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600070] = {
    id = 600070,
    GroupID = 45877,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600071] = {
    id = 600071,
    GroupID = 45878,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600072] = {
    id = 600072,
    GroupID = 45878,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600073] = {
    id = 600073,
    GroupID = 45878,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600074] = {
    id = 600074,
    GroupID = 45878,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600075] = {
    id = 600075,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600076] = {
    id = 600076,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600077] = {
    id = 600077,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600078] = {
    id = 600078,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600079] = {
    id = 600079,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600080] = {
    id = 600080,
    GroupID = 49036,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600081] = {
    id = 600081,
    GroupID = 49036,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600082] = {
    id = 600082,
    GroupID = 49078,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600083] = {
    id = 600083,
    GroupID = 49079,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600084] = {
    id = 600084,
    GroupID = 49079,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600085] = {
    id = 600085,
    GroupID = 49078,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600086] = {
    id = 600086,
    GroupID = 3000104,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600087] = {
    id = 600087,
    GroupID = 3000104,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600088] = {
    id = 600088,
    GroupID = 3000104,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600089] = {
    id = 600089,
    GroupID = 3000104,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600090] = {
    id = 600090,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600091] = {
    id = 600091,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600092] = {
    id = 600092,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600093] = {
    id = 600093,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600094] = {
    id = 600094,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600095] = {
    id = 600095,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600096] = {
    id = 600096,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600097] = {
    id = 600097,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 327
  },
  [600098] = {
    id = 600098,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600099] = {
    id = 600099,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 259
  },
  [600100] = {
    id = 600100,
    GroupID = 3001379,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    RealShowModel = 2,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600101] = {
    id = 600101,
    GroupID = 3001379,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    RealShowModel = 2,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600102] = {
    id = 600102,
    GroupID = 3001379,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    RealShowModel = 2,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600103] = {
    id = 600103,
    GroupID = 3001379,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    RealShowModel = 2,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600104] = {
    id = 600104,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600105] = {
    id = 600105,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600106] = {
    id = 600106,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600107] = {
    id = 600107,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 317
  },
  [600108] = {
    id = 600108,
    GroupID = 149260,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600109] = {
    id = 600109,
    Type = "Mouth",
    EquipType = 13,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600110] = {
    id = 600110,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600111] = {
    id = 600111,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600112] = {
    id = 600112,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600113] = {
    id = 600113,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600114] = {
    id = 600114,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 202
  },
  [600115] = {
    id = 600115,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 202
  },
  [600116] = {
    id = 600116,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 202
  },
  [600117] = {
    id = 600117,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 202
  },
  [600118] = {
    id = 600118,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 202
  },
  [600119] = {
    id = 600119,
    GroupID = 3002143,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 202
  },
  [600120] = {
    id = 600120,
    GroupID = 3002143,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 202
  },
  [600121] = {
    id = 600121,
    GroupID = 3002143,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 202
  },
  [600122] = {
    id = 600122,
    GroupID = 3002143,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 202
  },
  [600123] = {
    id = 600123,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 202
  },
  [600124] = {
    id = 600124,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600125] = {
    id = 600125,
    GroupID = 3002264,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 348
  },
  [600126] = {
    id = 600126,
    GroupID = 3002264,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 348
  },
  [600127] = {
    id = 600127,
    GroupID = 3002264,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 348
  },
  [600128] = {
    id = 600128,
    GroupID = 3002264,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 348
  },
  [600129] = {
    id = 600129,
    GroupID = 3002269,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600130] = {
    id = 600130,
    GroupID = 3002269,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600131] = {
    id = 600131,
    GroupID = 3002269,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600132] = {
    id = 600132,
    GroupID = 3002269,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600133] = {
    id = 600133,
    GroupID = 3002489,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600134] = {
    id = 600134,
    GroupID = 3002489,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600135] = {
    id = 600135,
    GroupID = 3002489,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600136] = {
    id = 600136,
    GroupID = 3002489,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600137] = {
    id = 600137,
    GroupID = 3002408,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600138] = {
    id = 600138,
    GroupID = 3002408,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600139] = {
    id = 600139,
    GroupID = 3002408,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600140] = {
    id = 600140,
    GroupID = 3002408,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600141] = {
    id = 600141,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600142] = {
    id = 600142,
    GroupID = 3002874,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600143] = {
    id = 600143,
    GroupID = 3002874,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600144] = {
    id = 600144,
    GroupID = 3002874,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600145] = {
    id = 600145,
    GroupID = 3002874,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600146] = {
    id = 600146,
    GroupID = 3002879,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600147] = {
    id = 600147,
    GroupID = 3002879,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600148] = {
    id = 600148,
    GroupID = 3002879,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600149] = {
    id = 600149,
    GroupID = 3002879,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600150] = {
    id = 600150,
    GroupID = 49536,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600151] = {
    id = 600151,
    GroupID = 49536,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600152] = {
    id = 600152,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600153] = {
    id = 600153,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600154] = {
    id = 600154,
    GroupID = 149518,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600155] = {
    id = 600155,
    GroupID = 149518,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600156] = {
    id = 600156,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600157] = {
    id = 600157,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600158] = {
    id = 600158,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 237
  },
  [600159] = {
    id = 600159,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 326
  },
  [600160] = {
    id = 600160,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 297
  },
  [600161] = {
    id = 600161,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 254
  },
  [600162] = {
    id = 600162,
    GroupID = 3003194,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600163] = {
    id = 600163,
    GroupID = 3003194,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600164] = {
    id = 600164,
    GroupID = 3003194,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600165] = {
    id = 600165,
    GroupID = 3003194,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600166] = {
    id = 600166,
    GroupID = 3003199,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600167] = {
    id = 600167,
    GroupID = 3003199,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600168] = {
    id = 600168,
    GroupID = 3003199,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600169] = {
    id = 600169,
    GroupID = 3003199,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    ShadowOff = 0,
    TemplateID = 35
  },
  [600170] = {
    id = 600170,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600171] = {
    id = 600171,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 1019
  },
  [600172] = {
    id = 600172,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600173] = {
    id = 600173,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600174] = {
    id = 600174,
    GroupID = 3003344,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600175] = {
    id = 600175,
    GroupID = 3003344,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600176] = {
    id = 600176,
    GroupID = 3003344,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600177] = {
    id = 600177,
    GroupID = 3003344,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600178] = {
    id = 600178,
    GroupID = 3003349,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600179] = {
    id = 600179,
    GroupID = 3003349,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600180] = {
    id = 600180,
    GroupID = 3003349,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600181] = {
    id = 600181,
    GroupID = 3003349,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600182] = {
    id = 600182,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600183] = {
    id = 600183,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600184] = {
    id = 600184,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 301
  },
  [600185] = {
    id = 600185,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600186] = {
    id = 600186,
    Type = "Mouth",
    EquipType = 13,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    ShadowOff = 0,
    TemplateID = 134
  },
  [600187] = {
    id = 600187,
    GroupID = 3003719,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600188] = {
    id = 600188,
    GroupID = 3003719,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600189] = {
    id = 600189,
    GroupID = 3003719,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600190] = {
    id = 600190,
    GroupID = 3003719,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600191] = {
    id = 600191,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600192] = {
    id = 600192,
    GroupID = 3003493,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600193] = {
    id = 600193,
    GroupID = 3003493,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600194] = {
    id = 600194,
    GroupID = 3003752,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600195] = {
    id = 600195,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600196] = {
    id = 600196,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600197] = {
    id = 600197,
    GroupID = 3003415,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600198] = {
    id = 600198,
    GroupID = 3003415,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    Feature = 2,
    TemplateID = 35
  },
  [600199] = {
    id = 600199,
    GroupID = 3003415,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600200] = {
    id = 600200,
    GroupID = 3003415,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600201] = {
    id = 600201,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600202] = {
    id = 600202,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600203] = {
    id = 600203,
    GroupID = 3004913,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600204] = {
    id = 600204,
    GroupID = 3004913,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600205] = {
    id = 600205,
    GroupID = 3004913,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600206] = {
    id = 600206,
    GroupID = 3004913,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 35
  },
  [600207] = {
    id = 600207,
    GroupID = 3005289,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 356
  },
  [600208] = {
    id = 600208,
    GroupID = 3005289,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 356
  },
  [600209] = {
    id = 600209,
    GroupID = 3005289,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 356
  },
  [600221] = {
    id = 600221,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 366
  },
  [600230] = {
    id = 600230,
    GroupID = 3006279,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 356
  },
  [600231] = {
    id = 600231,
    GroupID = 3006279,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600232] = {
    id = 600232,
    GroupID = 3006279,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600233] = {
    id = 600233,
    GroupID = 3006279,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600234] = {
    id = 600234,
    GroupID = 3006154,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600235] = {
    id = 600235,
    GroupID = 3006154,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600236] = {
    id = 600236,
    GroupID = 3006154,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600237] = {
    id = 600237,
    GroupID = 3006154,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600238] = {
    id = 600238,
    GroupID = 3006159,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600239] = {
    id = 600239,
    GroupID = 3006159,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600240] = {
    id = 600240,
    GroupID = 3006159,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600241] = {
    id = 600241,
    GroupID = 3006159,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600243] = {
    id = 600243,
    GroupID = 49605,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600244] = {
    id = 600244,
    GroupID = 49605,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600247] = {
    id = 600247,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600248] = {
    id = 600248,
    GroupID = 3006464,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600249] = {
    id = 600249,
    GroupID = 3006464,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600250] = {
    id = 600250,
    GroupID = 3006464,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600251] = {
    id = 600251,
    GroupID = 3006464,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600252] = {
    id = 600252,
    GroupID = 3006469,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600253] = {
    id = 600253,
    GroupID = 3006469,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600254] = {
    id = 600254,
    GroupID = 3006469,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600255] = {
    id = 600255,
    GroupID = 3006469,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600256] = {
    id = 600256,
    Type = "Face",
    EquipType = 10,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600257] = {
    id = 600257,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = {RefineMDamReduc = 0.008},
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600258] = {
    id = 600258,
    GroupID = 3006594,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600259] = {
    id = 600259,
    GroupID = 3006594,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600260] = {
    id = 600260,
    GroupID = 3006594,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600261] = {
    id = 600261,
    GroupID = 3006594,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600262] = {
    id = 600262,
    GroupID = 3006599,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600263] = {
    id = 600263,
    GroupID = 3006599,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600264] = {
    id = 600264,
    GroupID = 3006599,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600265] = {
    id = 600265,
    GroupID = 3006599,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600266] = {
    id = 600266,
    GroupID = 3006724,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600267] = {
    id = 600267,
    GroupID = 3006724,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600268] = {
    id = 600268,
    GroupID = 3006724,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600269] = {
    id = 600269,
    GroupID = 3006724,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600270] = {
    id = 600270,
    GroupID = 3006729,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600271] = {
    id = 600271,
    GroupID = 3006729,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600272] = {
    id = 600272,
    GroupID = 3006729,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600273] = {
    id = 600273,
    GroupID = 3006729,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600274] = {
    id = 600274,
    GroupID = 3006984,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600275] = {
    id = 600275,
    GroupID = 3006984,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600276] = {
    id = 600276,
    GroupID = 3006984,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600277] = {
    id = 600277,
    GroupID = 3006984,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600278] = {
    id = 600278,
    GroupID = 3006989,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600279] = {
    id = 600279,
    GroupID = 3006989,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600280] = {
    id = 600280,
    GroupID = 3006989,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600281] = {
    id = 600281,
    GroupID = 3006989,
    Type = "Head",
    EquipType = 8,
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable
  },
  [600292] = {
    id = 600292,
    Type = "Head",
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 4180
  },
  [600293] = {
    id = 600293,
    Type = "Head",
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 4182
  },
  [600294] = {
    id = 600294,
    GroupID = 3006765,
    Type = "Head",
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 4181
  },
  [600295] = {
    id = 600295,
    GroupID = 3006765,
    Type = "Head",
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 4181
  },
  [600296] = {
    id = 600296,
    Type = "Head",
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 4182
  },
  [600297] = {
    id = 600297,
    Type = "Head",
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 4182
  },
  [600298] = {
    id = 600298,
    Type = "Face",
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 4172
  },
  [600299] = {
    id = 600299,
    Type = "Face",
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 4172
  },
  [600300] = {
    id = 600300,
    Type = "Head",
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 4180
  },
  [600301] = {
    id = 600301,
    Type = "Face",
    FashionBuff = _EmptyTable,
    RefineEffect = _EmptyTable,
    SE_hit = "",
    PVPEffect = _EmptyTable,
    PVPUniqueEffect = _EmptyTable,
    EquipCondition = _EmptyTable,
    RelatedShow = _EmptyTable,
    RefinePerformance = _EmptyTable,
    TemplateID = 4172
  }
}
Table_EquipFake_fields = {
  "id",
  "GroupID",
  "Type",
  "EquipType",
  "FashionBuff",
  "RefineEffect",
  "SE_hit",
  "ReplaceValues",
  "SubstituteID",
  "UpgradeID",
  "DecomposeID",
  "DecomposeNum",
  "Body",
  "PVPEffect",
  "PVPUniqueEffect",
  "RealShowModel",
  "CanEquip",
  "EquipCondition",
  "RelatedShow",
  "RefinePerformance",
  "DisplayForbid",
  "Feature",
  "ShadowOff",
  "TemplateID"
}
return Table_EquipFake
