local ReconnInitCommand = class("ReconnInitCommand", pm.SimpleCommand)
function ReconnInitCommand:execute(note)
  self:Init()
end
function ReconnInitCommand:Init()
  if Game.Myself then
    Game.Myself:Client_ClearFollower()
    Game.Myself:Server_SetHandInHand(Game.Myself:Client_GetFollowLeaderID(), false)
  end
  ServiceItemProxy.Instance:CallPackageItem(SceneItem_pb.EPACKTYPE_WALLET)
  ServiceItemProxy.Instance:CallPackageItem(SceneItem_pb.EPACKTYPE_MAIN)
  ServiceItemProxy.Instance:CallPackageItem(SceneItem_pb.EPACKTYPE_EQUIP)
  ServiceItemProxy.Instance:CallPackageItem(SceneItem_pb.EPACKTYPE_FASHIONEQUIP)
  ServiceItemProxy.Instance:CallPackageItem(SceneItem_pb.EPACKTYPE_STORE)
  ServiceItemProxy.Instance:CallPackageItem(SceneItem_pb.EPACKTYPE_PERSONAL_STORE)
  ServiceItemProxy.Instance:CallPackageItem(SceneItem_pb.EPACKTYPE_TEMP_MAIN)
  ServiceItemProxy.Instance:CallPackageItem(SceneItem_pb.EPACKTYPE_QUEST or 10)
  ServiceItemProxy.Instance:CallPackageItem(SceneItem_pb.EPACKTYPE_FOOD or 11)
  ServiceItemProxy.Instance:CallPackageItem(SceneItem_pb.EPACKTYPE_PET or 12)
  ServiceItemProxy.Instance:CallPackageItem(SceneItem_pb.EPACKTYPE_GEM_ATTR)
  ServiceItemProxy.Instance:CallPackageItem(SceneItem_pb.EPACKTYPE_GEM_SKILL)
  ServiceItemProxy.Instance:CallPackageItem(SceneItem_pb.EPACKTYPE_ARTIFACT)
  ServiceItemProxy.Instance:CallPackageItem(SceneItem_pb.EPACKTYPE_ARTIFACT_FLAGMENT)
  redlog("---------------------ReconnInitCommand 请求背包")
  GameFacade.Instance:sendNotification(ServiceEvent.ReloadDatas)
  ServiceNUserProxy.Instance:CallQueryShopGotItem()
  ServiceNUserProxy.Instance:CallNewDressing()
  FunctionGuide.Me():stopGuide()
  FunctionCheck.Me():Reset()
  FloatingPanel.Instance:CloseMaintenanceMsg()
  ComboCtl.Instance:Clear()
  QuestProxy.Instance:CleanAllQuest()
  PvpProxy.Instance:Reconnect()
  PlotAudioProxy.Instance:ResetAll()
  DungeonProxy.Instance:Reconnect()
  Game.PlotStoryManager:Clear()
  Game.PlotStoryManager:ClearMyTempEffect()
  PveEntranceProxy.Instance:PreprocessTable()
  FunctionPve.QueryPvePassInfo()
end
return ReconnInitCommand
