local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
module("GoalCmd_pb")
GOALPARAM = protobuf.EnumDescriptor()
GOALPARAM_GOALPARAM_QUERY_LIST_ENUM = protobuf.EnumValueDescriptor()
GOALPARAM_GOALPARAM_UPDATE_ITEM_ENUM = protobuf.EnumValueDescriptor()
GOALPARAM_GOALPARAM_UPDATE_GROUP_ENUM = protobuf.EnumValueDescriptor()
GOALPARAM_GOALPARAM_UPDATE_SCORE_ENUM = protobuf.EnumValueDescriptor()
GOALPARAM_GOALPARAM_GET_GROUP_REWARD_ENUM = protobuf.EnumValueDescriptor()
GOALPARAM_GOALPARAM_GET_ITEM_SCORE_ENUM = protobuf.EnumValueDescriptor()
GOALPARAM_GOALPARAM_GET_SCORE_REWARD_ENUM = protobuf.EnumValueDescriptor()
EGOALSTATUS = protobuf.EnumDescriptor()
EGOALSTATUS_EGOALSTATUS_MIN_ENUM = protobuf.EnumValueDescriptor()
EGOALSTATUS_EGOALSTATUS_ACTIVE_ENUM = protobuf.EnumValueDescriptor()
EGOALSTATUS_EGOALSTATUS_FINISH_ENUM = protobuf.EnumValueDescriptor()
EGOALSTATUS_EGOALSTATUS_MAX_ENUM = protobuf.EnumValueDescriptor()
GOALSCORE = protobuf.Descriptor()
GOALSCORE_VERSION_FIELD = protobuf.FieldDescriptor()
GOALSCORE_SCORE_FIELD = protobuf.FieldDescriptor()
GOALSCORE_REWARDS_FIELD = protobuf.FieldDescriptor()
GOALITEM = protobuf.Descriptor()
GOALITEM_ID_FIELD = protobuf.FieldDescriptor()
GOALITEM_PROCESS_FIELD = protobuf.FieldDescriptor()
GOALITEM_STATUS_FIELD = protobuf.FieldDescriptor()
GOALITEM_POINT_FIELD = protobuf.FieldDescriptor()
GOALGROUP = protobuf.Descriptor()
GOALGROUP_GROUP_FIELD = protobuf.FieldDescriptor()
GOALGROUP_REWARDCOUNT_FIELD = protobuf.FieldDescriptor()
QUERYGOALLISTGOALCMD = protobuf.Descriptor()
QUERYGOALLISTGOALCMD_CMD_FIELD = protobuf.FieldDescriptor()
QUERYGOALLISTGOALCMD_PARAM_FIELD = protobuf.FieldDescriptor()
QUERYGOALLISTGOALCMD_VERSION_FIELD = protobuf.FieldDescriptor()
QUERYGOALLISTGOALCMD_ITEMS_FIELD = protobuf.FieldDescriptor()
QUERYGOALLISTGOALCMD_GROUPS_FIELD = protobuf.FieldDescriptor()
QUERYGOALLISTGOALCMD_SCORE_FIELD = protobuf.FieldDescriptor()
NEWGOALITEMUPDATEGOALCMD = protobuf.Descriptor()
NEWGOALITEMUPDATEGOALCMD_CMD_FIELD = protobuf.FieldDescriptor()
NEWGOALITEMUPDATEGOALCMD_PARAM_FIELD = protobuf.FieldDescriptor()
NEWGOALITEMUPDATEGOALCMD_ITEM_FIELD = protobuf.FieldDescriptor()
NEWGROUPUPDATEGOALCMD = protobuf.Descriptor()
NEWGROUPUPDATEGOALCMD_CMD_FIELD = protobuf.FieldDescriptor()
NEWGROUPUPDATEGOALCMD_PARAM_FIELD = protobuf.FieldDescriptor()
NEWGROUPUPDATEGOALCMD_GROUP_FIELD = protobuf.FieldDescriptor()
NEWGOALSCOREUPDATEGOALCMD = protobuf.Descriptor()
NEWGOALSCOREUPDATEGOALCMD_CMD_FIELD = protobuf.FieldDescriptor()
NEWGOALSCOREUPDATEGOALCMD_PARAM_FIELD = protobuf.FieldDescriptor()
NEWGOALSCOREUPDATEGOALCMD_SCORE_FIELD = protobuf.FieldDescriptor()
GETGROUPREWARDGOALCMD = protobuf.Descriptor()
GETGROUPREWARDGOALCMD_CMD_FIELD = protobuf.FieldDescriptor()
GETGROUPREWARDGOALCMD_PARAM_FIELD = protobuf.FieldDescriptor()
GETGROUPREWARDGOALCMD_GROUP_FIELD = protobuf.FieldDescriptor()
GETSCOREGOALCMD = protobuf.Descriptor()
GETSCOREGOALCMD_CMD_FIELD = protobuf.FieldDescriptor()
GETSCOREGOALCMD_PARAM_FIELD = protobuf.FieldDescriptor()
GETSCOREGOALCMD_ID_FIELD = protobuf.FieldDescriptor()
GETSCOREREWARDGOALCMD = protobuf.Descriptor()
GETSCOREREWARDGOALCMD_CMD_FIELD = protobuf.FieldDescriptor()
GETSCOREREWARDGOALCMD_PARAM_FIELD = protobuf.FieldDescriptor()
GETSCOREREWARDGOALCMD_VERSION_FIELD = protobuf.FieldDescriptor()
GETSCOREREWARDGOALCMD_VALUE_FIELD = protobuf.FieldDescriptor()
GOALPARAM_GOALPARAM_QUERY_LIST_ENUM.name = "GOALPARAM_QUERY_LIST"
GOALPARAM_GOALPARAM_QUERY_LIST_ENUM.index = 0
GOALPARAM_GOALPARAM_QUERY_LIST_ENUM.number = 1
GOALPARAM_GOALPARAM_UPDATE_ITEM_ENUM.name = "GOALPARAM_UPDATE_ITEM"
GOALPARAM_GOALPARAM_UPDATE_ITEM_ENUM.index = 1
GOALPARAM_GOALPARAM_UPDATE_ITEM_ENUM.number = 2
GOALPARAM_GOALPARAM_UPDATE_GROUP_ENUM.name = "GOALPARAM_UPDATE_GROUP"
GOALPARAM_GOALPARAM_UPDATE_GROUP_ENUM.index = 2
GOALPARAM_GOALPARAM_UPDATE_GROUP_ENUM.number = 3
GOALPARAM_GOALPARAM_UPDATE_SCORE_ENUM.name = "GOALPARAM_UPDATE_SCORE"
GOALPARAM_GOALPARAM_UPDATE_SCORE_ENUM.index = 3
GOALPARAM_GOALPARAM_UPDATE_SCORE_ENUM.number = 4
GOALPARAM_GOALPARAM_GET_GROUP_REWARD_ENUM.name = "GOALPARAM_GET_GROUP_REWARD"
GOALPARAM_GOALPARAM_GET_GROUP_REWARD_ENUM.index = 4
GOALPARAM_GOALPARAM_GET_GROUP_REWARD_ENUM.number = 5
GOALPARAM_GOALPARAM_GET_ITEM_SCORE_ENUM.name = "GOALPARAM_GET_ITEM_SCORE"
GOALPARAM_GOALPARAM_GET_ITEM_SCORE_ENUM.index = 5
GOALPARAM_GOALPARAM_GET_ITEM_SCORE_ENUM.number = 6
GOALPARAM_GOALPARAM_GET_SCORE_REWARD_ENUM.name = "GOALPARAM_GET_SCORE_REWARD"
GOALPARAM_GOALPARAM_GET_SCORE_REWARD_ENUM.index = 6
GOALPARAM_GOALPARAM_GET_SCORE_REWARD_ENUM.number = 7
GOALPARAM.name = "GoalParam"
GOALPARAM.full_name = ".Cmd.GoalParam"
GOALPARAM.values = {
  GOALPARAM_GOALPARAM_QUERY_LIST_ENUM,
  GOALPARAM_GOALPARAM_UPDATE_ITEM_ENUM,
  GOALPARAM_GOALPARAM_UPDATE_GROUP_ENUM,
  GOALPARAM_GOALPARAM_UPDATE_SCORE_ENUM,
  GOALPARAM_GOALPARAM_GET_GROUP_REWARD_ENUM,
  GOALPARAM_GOALPARAM_GET_ITEM_SCORE_ENUM,
  GOALPARAM_GOALPARAM_GET_SCORE_REWARD_ENUM
}
EGOALSTATUS_EGOALSTATUS_MIN_ENUM.name = "EGOALSTATUS_MIN"
EGOALSTATUS_EGOALSTATUS_MIN_ENUM.index = 0
EGOALSTATUS_EGOALSTATUS_MIN_ENUM.number = 0
EGOALSTATUS_EGOALSTATUS_ACTIVE_ENUM.name = "EGOALSTATUS_ACTIVE"
EGOALSTATUS_EGOALSTATUS_ACTIVE_ENUM.index = 1
EGOALSTATUS_EGOALSTATUS_ACTIVE_ENUM.number = 1
EGOALSTATUS_EGOALSTATUS_FINISH_ENUM.name = "EGOALSTATUS_FINISH"
EGOALSTATUS_EGOALSTATUS_FINISH_ENUM.index = 2
EGOALSTATUS_EGOALSTATUS_FINISH_ENUM.number = 2
EGOALSTATUS_EGOALSTATUS_MAX_ENUM.name = "EGOALSTATUS_MAX"
EGOALSTATUS_EGOALSTATUS_MAX_ENUM.index = 3
EGOALSTATUS_EGOALSTATUS_MAX_ENUM.number = 3
EGOALSTATUS.name = "EGoalStatus"
EGOALSTATUS.full_name = ".Cmd.EGoalStatus"
EGOALSTATUS.values = {
  EGOALSTATUS_EGOALSTATUS_MIN_ENUM,
  EGOALSTATUS_EGOALSTATUS_ACTIVE_ENUM,
  EGOALSTATUS_EGOALSTATUS_FINISH_ENUM,
  EGOALSTATUS_EGOALSTATUS_MAX_ENUM
}
GOALSCORE_VERSION_FIELD.name = "version"
GOALSCORE_VERSION_FIELD.full_name = ".Cmd.GoalScore.version"
GOALSCORE_VERSION_FIELD.number = 1
GOALSCORE_VERSION_FIELD.index = 0
GOALSCORE_VERSION_FIELD.label = 1
GOALSCORE_VERSION_FIELD.has_default_value = false
GOALSCORE_VERSION_FIELD.default_value = ""
GOALSCORE_VERSION_FIELD.type = 9
GOALSCORE_VERSION_FIELD.cpp_type = 9
GOALSCORE_SCORE_FIELD.name = "score"
GOALSCORE_SCORE_FIELD.full_name = ".Cmd.GoalScore.score"
GOALSCORE_SCORE_FIELD.number = 2
GOALSCORE_SCORE_FIELD.index = 1
GOALSCORE_SCORE_FIELD.label = 1
GOALSCORE_SCORE_FIELD.has_default_value = false
GOALSCORE_SCORE_FIELD.default_value = 0
GOALSCORE_SCORE_FIELD.type = 13
GOALSCORE_SCORE_FIELD.cpp_type = 3
GOALSCORE_REWARDS_FIELD.name = "rewards"
GOALSCORE_REWARDS_FIELD.full_name = ".Cmd.GoalScore.rewards"
GOALSCORE_REWARDS_FIELD.number = 3
GOALSCORE_REWARDS_FIELD.index = 2
GOALSCORE_REWARDS_FIELD.label = 3
GOALSCORE_REWARDS_FIELD.has_default_value = false
GOALSCORE_REWARDS_FIELD.default_value = {}
GOALSCORE_REWARDS_FIELD.type = 13
GOALSCORE_REWARDS_FIELD.cpp_type = 3
GOALSCORE.name = "GoalScore"
GOALSCORE.full_name = ".Cmd.GoalScore"
GOALSCORE.nested_types = {}
GOALSCORE.enum_types = {}
GOALSCORE.fields = {
  GOALSCORE_VERSION_FIELD,
  GOALSCORE_SCORE_FIELD,
  GOALSCORE_REWARDS_FIELD
}
GOALSCORE.is_extendable = false
GOALSCORE.extensions = {}
GOALITEM_ID_FIELD.name = "id"
GOALITEM_ID_FIELD.full_name = ".Cmd.GoalItem.id"
GOALITEM_ID_FIELD.number = 1
GOALITEM_ID_FIELD.index = 0
GOALITEM_ID_FIELD.label = 1
GOALITEM_ID_FIELD.has_default_value = false
GOALITEM_ID_FIELD.default_value = 0
GOALITEM_ID_FIELD.type = 13
GOALITEM_ID_FIELD.cpp_type = 3
GOALITEM_PROCESS_FIELD.name = "process"
GOALITEM_PROCESS_FIELD.full_name = ".Cmd.GoalItem.process"
GOALITEM_PROCESS_FIELD.number = 2
GOALITEM_PROCESS_FIELD.index = 1
GOALITEM_PROCESS_FIELD.label = 1
GOALITEM_PROCESS_FIELD.has_default_value = false
GOALITEM_PROCESS_FIELD.default_value = 0
GOALITEM_PROCESS_FIELD.type = 13
GOALITEM_PROCESS_FIELD.cpp_type = 3
GOALITEM_STATUS_FIELD.name = "status"
GOALITEM_STATUS_FIELD.full_name = ".Cmd.GoalItem.status"
GOALITEM_STATUS_FIELD.number = 3
GOALITEM_STATUS_FIELD.index = 2
GOALITEM_STATUS_FIELD.label = 1
GOALITEM_STATUS_FIELD.has_default_value = false
GOALITEM_STATUS_FIELD.default_value = nil
GOALITEM_STATUS_FIELD.enum_type = EGOALSTATUS
GOALITEM_STATUS_FIELD.type = 14
GOALITEM_STATUS_FIELD.cpp_type = 8
GOALITEM_POINT_FIELD.name = "point"
GOALITEM_POINT_FIELD.full_name = ".Cmd.GoalItem.point"
GOALITEM_POINT_FIELD.number = 4
GOALITEM_POINT_FIELD.index = 3
GOALITEM_POINT_FIELD.label = 1
GOALITEM_POINT_FIELD.has_default_value = false
GOALITEM_POINT_FIELD.default_value = false
GOALITEM_POINT_FIELD.type = 8
GOALITEM_POINT_FIELD.cpp_type = 7
GOALITEM.name = "GoalItem"
GOALITEM.full_name = ".Cmd.GoalItem"
GOALITEM.nested_types = {}
GOALITEM.enum_types = {}
GOALITEM.fields = {
  GOALITEM_ID_FIELD,
  GOALITEM_PROCESS_FIELD,
  GOALITEM_STATUS_FIELD,
  GOALITEM_POINT_FIELD
}
GOALITEM.is_extendable = false
GOALITEM.extensions = {}
GOALGROUP_GROUP_FIELD.name = "group"
GOALGROUP_GROUP_FIELD.full_name = ".Cmd.GoalGroup.group"
GOALGROUP_GROUP_FIELD.number = 1
GOALGROUP_GROUP_FIELD.index = 0
GOALGROUP_GROUP_FIELD.label = 1
GOALGROUP_GROUP_FIELD.has_default_value = false
GOALGROUP_GROUP_FIELD.default_value = 0
GOALGROUP_GROUP_FIELD.type = 13
GOALGROUP_GROUP_FIELD.cpp_type = 3
GOALGROUP_REWARDCOUNT_FIELD.name = "rewardcount"
GOALGROUP_REWARDCOUNT_FIELD.full_name = ".Cmd.GoalGroup.rewardcount"
GOALGROUP_REWARDCOUNT_FIELD.number = 2
GOALGROUP_REWARDCOUNT_FIELD.index = 1
GOALGROUP_REWARDCOUNT_FIELD.label = 1
GOALGROUP_REWARDCOUNT_FIELD.has_default_value = false
GOALGROUP_REWARDCOUNT_FIELD.default_value = 0
GOALGROUP_REWARDCOUNT_FIELD.type = 13
GOALGROUP_REWARDCOUNT_FIELD.cpp_type = 3
GOALGROUP.name = "GoalGroup"
GOALGROUP.full_name = ".Cmd.GoalGroup"
GOALGROUP.nested_types = {}
GOALGROUP.enum_types = {}
GOALGROUP.fields = {
  GOALGROUP_GROUP_FIELD,
  GOALGROUP_REWARDCOUNT_FIELD
}
GOALGROUP.is_extendable = false
GOALGROUP.extensions = {}
QUERYGOALLISTGOALCMD_CMD_FIELD.name = "cmd"
QUERYGOALLISTGOALCMD_CMD_FIELD.full_name = ".Cmd.QueryGoalListGoalCmd.cmd"
QUERYGOALLISTGOALCMD_CMD_FIELD.number = 1
QUERYGOALLISTGOALCMD_CMD_FIELD.index = 0
QUERYGOALLISTGOALCMD_CMD_FIELD.label = 1
QUERYGOALLISTGOALCMD_CMD_FIELD.has_default_value = true
QUERYGOALLISTGOALCMD_CMD_FIELD.default_value = 75
QUERYGOALLISTGOALCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
QUERYGOALLISTGOALCMD_CMD_FIELD.type = 14
QUERYGOALLISTGOALCMD_CMD_FIELD.cpp_type = 8
QUERYGOALLISTGOALCMD_PARAM_FIELD.name = "param"
QUERYGOALLISTGOALCMD_PARAM_FIELD.full_name = ".Cmd.QueryGoalListGoalCmd.param"
QUERYGOALLISTGOALCMD_PARAM_FIELD.number = 2
QUERYGOALLISTGOALCMD_PARAM_FIELD.index = 1
QUERYGOALLISTGOALCMD_PARAM_FIELD.label = 1
QUERYGOALLISTGOALCMD_PARAM_FIELD.has_default_value = true
QUERYGOALLISTGOALCMD_PARAM_FIELD.default_value = 1
QUERYGOALLISTGOALCMD_PARAM_FIELD.enum_type = GOALPARAM
QUERYGOALLISTGOALCMD_PARAM_FIELD.type = 14
QUERYGOALLISTGOALCMD_PARAM_FIELD.cpp_type = 8
QUERYGOALLISTGOALCMD_VERSION_FIELD.name = "version"
QUERYGOALLISTGOALCMD_VERSION_FIELD.full_name = ".Cmd.QueryGoalListGoalCmd.version"
QUERYGOALLISTGOALCMD_VERSION_FIELD.number = 3
QUERYGOALLISTGOALCMD_VERSION_FIELD.index = 2
QUERYGOALLISTGOALCMD_VERSION_FIELD.label = 1
QUERYGOALLISTGOALCMD_VERSION_FIELD.has_default_value = false
QUERYGOALLISTGOALCMD_VERSION_FIELD.default_value = ""
QUERYGOALLISTGOALCMD_VERSION_FIELD.type = 9
QUERYGOALLISTGOALCMD_VERSION_FIELD.cpp_type = 9
QUERYGOALLISTGOALCMD_ITEMS_FIELD.name = "items"
QUERYGOALLISTGOALCMD_ITEMS_FIELD.full_name = ".Cmd.QueryGoalListGoalCmd.items"
QUERYGOALLISTGOALCMD_ITEMS_FIELD.number = 4
QUERYGOALLISTGOALCMD_ITEMS_FIELD.index = 3
QUERYGOALLISTGOALCMD_ITEMS_FIELD.label = 3
QUERYGOALLISTGOALCMD_ITEMS_FIELD.has_default_value = false
QUERYGOALLISTGOALCMD_ITEMS_FIELD.default_value = {}
QUERYGOALLISTGOALCMD_ITEMS_FIELD.message_type = GOALITEM
QUERYGOALLISTGOALCMD_ITEMS_FIELD.type = 11
QUERYGOALLISTGOALCMD_ITEMS_FIELD.cpp_type = 10
QUERYGOALLISTGOALCMD_GROUPS_FIELD.name = "groups"
QUERYGOALLISTGOALCMD_GROUPS_FIELD.full_name = ".Cmd.QueryGoalListGoalCmd.groups"
QUERYGOALLISTGOALCMD_GROUPS_FIELD.number = 5
QUERYGOALLISTGOALCMD_GROUPS_FIELD.index = 4
QUERYGOALLISTGOALCMD_GROUPS_FIELD.label = 3
QUERYGOALLISTGOALCMD_GROUPS_FIELD.has_default_value = false
QUERYGOALLISTGOALCMD_GROUPS_FIELD.default_value = {}
QUERYGOALLISTGOALCMD_GROUPS_FIELD.message_type = GOALGROUP
QUERYGOALLISTGOALCMD_GROUPS_FIELD.type = 11
QUERYGOALLISTGOALCMD_GROUPS_FIELD.cpp_type = 10
QUERYGOALLISTGOALCMD_SCORE_FIELD.name = "score"
QUERYGOALLISTGOALCMD_SCORE_FIELD.full_name = ".Cmd.QueryGoalListGoalCmd.score"
QUERYGOALLISTGOALCMD_SCORE_FIELD.number = 6
QUERYGOALLISTGOALCMD_SCORE_FIELD.index = 5
QUERYGOALLISTGOALCMD_SCORE_FIELD.label = 1
QUERYGOALLISTGOALCMD_SCORE_FIELD.has_default_value = false
QUERYGOALLISTGOALCMD_SCORE_FIELD.default_value = nil
QUERYGOALLISTGOALCMD_SCORE_FIELD.message_type = GOALSCORE
QUERYGOALLISTGOALCMD_SCORE_FIELD.type = 11
QUERYGOALLISTGOALCMD_SCORE_FIELD.cpp_type = 10
QUERYGOALLISTGOALCMD.name = "QueryGoalListGoalCmd"
QUERYGOALLISTGOALCMD.full_name = ".Cmd.QueryGoalListGoalCmd"
QUERYGOALLISTGOALCMD.nested_types = {}
QUERYGOALLISTGOALCMD.enum_types = {}
QUERYGOALLISTGOALCMD.fields = {
  QUERYGOALLISTGOALCMD_CMD_FIELD,
  QUERYGOALLISTGOALCMD_PARAM_FIELD,
  QUERYGOALLISTGOALCMD_VERSION_FIELD,
  QUERYGOALLISTGOALCMD_ITEMS_FIELD,
  QUERYGOALLISTGOALCMD_GROUPS_FIELD,
  QUERYGOALLISTGOALCMD_SCORE_FIELD
}
QUERYGOALLISTGOALCMD.is_extendable = false
QUERYGOALLISTGOALCMD.extensions = {}
NEWGOALITEMUPDATEGOALCMD_CMD_FIELD.name = "cmd"
NEWGOALITEMUPDATEGOALCMD_CMD_FIELD.full_name = ".Cmd.NewGoalItemUpdateGoalCmd.cmd"
NEWGOALITEMUPDATEGOALCMD_CMD_FIELD.number = 1
NEWGOALITEMUPDATEGOALCMD_CMD_FIELD.index = 0
NEWGOALITEMUPDATEGOALCMD_CMD_FIELD.label = 1
NEWGOALITEMUPDATEGOALCMD_CMD_FIELD.has_default_value = true
NEWGOALITEMUPDATEGOALCMD_CMD_FIELD.default_value = 75
NEWGOALITEMUPDATEGOALCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
NEWGOALITEMUPDATEGOALCMD_CMD_FIELD.type = 14
NEWGOALITEMUPDATEGOALCMD_CMD_FIELD.cpp_type = 8
NEWGOALITEMUPDATEGOALCMD_PARAM_FIELD.name = "param"
NEWGOALITEMUPDATEGOALCMD_PARAM_FIELD.full_name = ".Cmd.NewGoalItemUpdateGoalCmd.param"
NEWGOALITEMUPDATEGOALCMD_PARAM_FIELD.number = 2
NEWGOALITEMUPDATEGOALCMD_PARAM_FIELD.index = 1
NEWGOALITEMUPDATEGOALCMD_PARAM_FIELD.label = 1
NEWGOALITEMUPDATEGOALCMD_PARAM_FIELD.has_default_value = true
NEWGOALITEMUPDATEGOALCMD_PARAM_FIELD.default_value = 2
NEWGOALITEMUPDATEGOALCMD_PARAM_FIELD.enum_type = GOALPARAM
NEWGOALITEMUPDATEGOALCMD_PARAM_FIELD.type = 14
NEWGOALITEMUPDATEGOALCMD_PARAM_FIELD.cpp_type = 8
NEWGOALITEMUPDATEGOALCMD_ITEM_FIELD.name = "item"
NEWGOALITEMUPDATEGOALCMD_ITEM_FIELD.full_name = ".Cmd.NewGoalItemUpdateGoalCmd.item"
NEWGOALITEMUPDATEGOALCMD_ITEM_FIELD.number = 3
NEWGOALITEMUPDATEGOALCMD_ITEM_FIELD.index = 2
NEWGOALITEMUPDATEGOALCMD_ITEM_FIELD.label = 1
NEWGOALITEMUPDATEGOALCMD_ITEM_FIELD.has_default_value = false
NEWGOALITEMUPDATEGOALCMD_ITEM_FIELD.default_value = nil
NEWGOALITEMUPDATEGOALCMD_ITEM_FIELD.message_type = GOALITEM
NEWGOALITEMUPDATEGOALCMD_ITEM_FIELD.type = 11
NEWGOALITEMUPDATEGOALCMD_ITEM_FIELD.cpp_type = 10
NEWGOALITEMUPDATEGOALCMD.name = "NewGoalItemUpdateGoalCmd"
NEWGOALITEMUPDATEGOALCMD.full_name = ".Cmd.NewGoalItemUpdateGoalCmd"
NEWGOALITEMUPDATEGOALCMD.nested_types = {}
NEWGOALITEMUPDATEGOALCMD.enum_types = {}
NEWGOALITEMUPDATEGOALCMD.fields = {
  NEWGOALITEMUPDATEGOALCMD_CMD_FIELD,
  NEWGOALITEMUPDATEGOALCMD_PARAM_FIELD,
  NEWGOALITEMUPDATEGOALCMD_ITEM_FIELD
}
NEWGOALITEMUPDATEGOALCMD.is_extendable = false
NEWGOALITEMUPDATEGOALCMD.extensions = {}
NEWGROUPUPDATEGOALCMD_CMD_FIELD.name = "cmd"
NEWGROUPUPDATEGOALCMD_CMD_FIELD.full_name = ".Cmd.NewGroupUpdateGoalCmd.cmd"
NEWGROUPUPDATEGOALCMD_CMD_FIELD.number = 1
NEWGROUPUPDATEGOALCMD_CMD_FIELD.index = 0
NEWGROUPUPDATEGOALCMD_CMD_FIELD.label = 1
NEWGROUPUPDATEGOALCMD_CMD_FIELD.has_default_value = true
NEWGROUPUPDATEGOALCMD_CMD_FIELD.default_value = 75
NEWGROUPUPDATEGOALCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
NEWGROUPUPDATEGOALCMD_CMD_FIELD.type = 14
NEWGROUPUPDATEGOALCMD_CMD_FIELD.cpp_type = 8
NEWGROUPUPDATEGOALCMD_PARAM_FIELD.name = "param"
NEWGROUPUPDATEGOALCMD_PARAM_FIELD.full_name = ".Cmd.NewGroupUpdateGoalCmd.param"
NEWGROUPUPDATEGOALCMD_PARAM_FIELD.number = 2
NEWGROUPUPDATEGOALCMD_PARAM_FIELD.index = 1
NEWGROUPUPDATEGOALCMD_PARAM_FIELD.label = 1
NEWGROUPUPDATEGOALCMD_PARAM_FIELD.has_default_value = true
NEWGROUPUPDATEGOALCMD_PARAM_FIELD.default_value = 3
NEWGROUPUPDATEGOALCMD_PARAM_FIELD.enum_type = GOALPARAM
NEWGROUPUPDATEGOALCMD_PARAM_FIELD.type = 14
NEWGROUPUPDATEGOALCMD_PARAM_FIELD.cpp_type = 8
NEWGROUPUPDATEGOALCMD_GROUP_FIELD.name = "group"
NEWGROUPUPDATEGOALCMD_GROUP_FIELD.full_name = ".Cmd.NewGroupUpdateGoalCmd.group"
NEWGROUPUPDATEGOALCMD_GROUP_FIELD.number = 3
NEWGROUPUPDATEGOALCMD_GROUP_FIELD.index = 2
NEWGROUPUPDATEGOALCMD_GROUP_FIELD.label = 1
NEWGROUPUPDATEGOALCMD_GROUP_FIELD.has_default_value = false
NEWGROUPUPDATEGOALCMD_GROUP_FIELD.default_value = nil
NEWGROUPUPDATEGOALCMD_GROUP_FIELD.message_type = GOALGROUP
NEWGROUPUPDATEGOALCMD_GROUP_FIELD.type = 11
NEWGROUPUPDATEGOALCMD_GROUP_FIELD.cpp_type = 10
NEWGROUPUPDATEGOALCMD.name = "NewGroupUpdateGoalCmd"
NEWGROUPUPDATEGOALCMD.full_name = ".Cmd.NewGroupUpdateGoalCmd"
NEWGROUPUPDATEGOALCMD.nested_types = {}
NEWGROUPUPDATEGOALCMD.enum_types = {}
NEWGROUPUPDATEGOALCMD.fields = {
  NEWGROUPUPDATEGOALCMD_CMD_FIELD,
  NEWGROUPUPDATEGOALCMD_PARAM_FIELD,
  NEWGROUPUPDATEGOALCMD_GROUP_FIELD
}
NEWGROUPUPDATEGOALCMD.is_extendable = false
NEWGROUPUPDATEGOALCMD.extensions = {}
NEWGOALSCOREUPDATEGOALCMD_CMD_FIELD.name = "cmd"
NEWGOALSCOREUPDATEGOALCMD_CMD_FIELD.full_name = ".Cmd.NewGoalScoreUpdateGoalCmd.cmd"
NEWGOALSCOREUPDATEGOALCMD_CMD_FIELD.number = 1
NEWGOALSCOREUPDATEGOALCMD_CMD_FIELD.index = 0
NEWGOALSCOREUPDATEGOALCMD_CMD_FIELD.label = 1
NEWGOALSCOREUPDATEGOALCMD_CMD_FIELD.has_default_value = true
NEWGOALSCOREUPDATEGOALCMD_CMD_FIELD.default_value = 75
NEWGOALSCOREUPDATEGOALCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
NEWGOALSCOREUPDATEGOALCMD_CMD_FIELD.type = 14
NEWGOALSCOREUPDATEGOALCMD_CMD_FIELD.cpp_type = 8
NEWGOALSCOREUPDATEGOALCMD_PARAM_FIELD.name = "param"
NEWGOALSCOREUPDATEGOALCMD_PARAM_FIELD.full_name = ".Cmd.NewGoalScoreUpdateGoalCmd.param"
NEWGOALSCOREUPDATEGOALCMD_PARAM_FIELD.number = 2
NEWGOALSCOREUPDATEGOALCMD_PARAM_FIELD.index = 1
NEWGOALSCOREUPDATEGOALCMD_PARAM_FIELD.label = 1
NEWGOALSCOREUPDATEGOALCMD_PARAM_FIELD.has_default_value = true
NEWGOALSCOREUPDATEGOALCMD_PARAM_FIELD.default_value = 4
NEWGOALSCOREUPDATEGOALCMD_PARAM_FIELD.enum_type = GOALPARAM
NEWGOALSCOREUPDATEGOALCMD_PARAM_FIELD.type = 14
NEWGOALSCOREUPDATEGOALCMD_PARAM_FIELD.cpp_type = 8
NEWGOALSCOREUPDATEGOALCMD_SCORE_FIELD.name = "score"
NEWGOALSCOREUPDATEGOALCMD_SCORE_FIELD.full_name = ".Cmd.NewGoalScoreUpdateGoalCmd.score"
NEWGOALSCOREUPDATEGOALCMD_SCORE_FIELD.number = 3
NEWGOALSCOREUPDATEGOALCMD_SCORE_FIELD.index = 2
NEWGOALSCOREUPDATEGOALCMD_SCORE_FIELD.label = 1
NEWGOALSCOREUPDATEGOALCMD_SCORE_FIELD.has_default_value = false
NEWGOALSCOREUPDATEGOALCMD_SCORE_FIELD.default_value = nil
NEWGOALSCOREUPDATEGOALCMD_SCORE_FIELD.message_type = GOALSCORE
NEWGOALSCOREUPDATEGOALCMD_SCORE_FIELD.type = 11
NEWGOALSCOREUPDATEGOALCMD_SCORE_FIELD.cpp_type = 10
NEWGOALSCOREUPDATEGOALCMD.name = "NewGoalScoreUpdateGoalCmd"
NEWGOALSCOREUPDATEGOALCMD.full_name = ".Cmd.NewGoalScoreUpdateGoalCmd"
NEWGOALSCOREUPDATEGOALCMD.nested_types = {}
NEWGOALSCOREUPDATEGOALCMD.enum_types = {}
NEWGOALSCOREUPDATEGOALCMD.fields = {
  NEWGOALSCOREUPDATEGOALCMD_CMD_FIELD,
  NEWGOALSCOREUPDATEGOALCMD_PARAM_FIELD,
  NEWGOALSCOREUPDATEGOALCMD_SCORE_FIELD
}
NEWGOALSCOREUPDATEGOALCMD.is_extendable = false
NEWGOALSCOREUPDATEGOALCMD.extensions = {}
GETGROUPREWARDGOALCMD_CMD_FIELD.name = "cmd"
GETGROUPREWARDGOALCMD_CMD_FIELD.full_name = ".Cmd.GetGroupRewardGoalCmd.cmd"
GETGROUPREWARDGOALCMD_CMD_FIELD.number = 1
GETGROUPREWARDGOALCMD_CMD_FIELD.index = 0
GETGROUPREWARDGOALCMD_CMD_FIELD.label = 1
GETGROUPREWARDGOALCMD_CMD_FIELD.has_default_value = true
GETGROUPREWARDGOALCMD_CMD_FIELD.default_value = 75
GETGROUPREWARDGOALCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
GETGROUPREWARDGOALCMD_CMD_FIELD.type = 14
GETGROUPREWARDGOALCMD_CMD_FIELD.cpp_type = 8
GETGROUPREWARDGOALCMD_PARAM_FIELD.name = "param"
GETGROUPREWARDGOALCMD_PARAM_FIELD.full_name = ".Cmd.GetGroupRewardGoalCmd.param"
GETGROUPREWARDGOALCMD_PARAM_FIELD.number = 2
GETGROUPREWARDGOALCMD_PARAM_FIELD.index = 1
GETGROUPREWARDGOALCMD_PARAM_FIELD.label = 1
GETGROUPREWARDGOALCMD_PARAM_FIELD.has_default_value = true
GETGROUPREWARDGOALCMD_PARAM_FIELD.default_value = 5
GETGROUPREWARDGOALCMD_PARAM_FIELD.enum_type = GOALPARAM
GETGROUPREWARDGOALCMD_PARAM_FIELD.type = 14
GETGROUPREWARDGOALCMD_PARAM_FIELD.cpp_type = 8
GETGROUPREWARDGOALCMD_GROUP_FIELD.name = "group"
GETGROUPREWARDGOALCMD_GROUP_FIELD.full_name = ".Cmd.GetGroupRewardGoalCmd.group"
GETGROUPREWARDGOALCMD_GROUP_FIELD.number = 3
GETGROUPREWARDGOALCMD_GROUP_FIELD.index = 2
GETGROUPREWARDGOALCMD_GROUP_FIELD.label = 1
GETGROUPREWARDGOALCMD_GROUP_FIELD.has_default_value = false
GETGROUPREWARDGOALCMD_GROUP_FIELD.default_value = 0
GETGROUPREWARDGOALCMD_GROUP_FIELD.type = 13
GETGROUPREWARDGOALCMD_GROUP_FIELD.cpp_type = 3
GETGROUPREWARDGOALCMD.name = "GetGroupRewardGoalCmd"
GETGROUPREWARDGOALCMD.full_name = ".Cmd.GetGroupRewardGoalCmd"
GETGROUPREWARDGOALCMD.nested_types = {}
GETGROUPREWARDGOALCMD.enum_types = {}
GETGROUPREWARDGOALCMD.fields = {
  GETGROUPREWARDGOALCMD_CMD_FIELD,
  GETGROUPREWARDGOALCMD_PARAM_FIELD,
  GETGROUPREWARDGOALCMD_GROUP_FIELD
}
GETGROUPREWARDGOALCMD.is_extendable = false
GETGROUPREWARDGOALCMD.extensions = {}
GETSCOREGOALCMD_CMD_FIELD.name = "cmd"
GETSCOREGOALCMD_CMD_FIELD.full_name = ".Cmd.GetScoreGoalCmd.cmd"
GETSCOREGOALCMD_CMD_FIELD.number = 1
GETSCOREGOALCMD_CMD_FIELD.index = 0
GETSCOREGOALCMD_CMD_FIELD.label = 1
GETSCOREGOALCMD_CMD_FIELD.has_default_value = true
GETSCOREGOALCMD_CMD_FIELD.default_value = 75
GETSCOREGOALCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
GETSCOREGOALCMD_CMD_FIELD.type = 14
GETSCOREGOALCMD_CMD_FIELD.cpp_type = 8
GETSCOREGOALCMD_PARAM_FIELD.name = "param"
GETSCOREGOALCMD_PARAM_FIELD.full_name = ".Cmd.GetScoreGoalCmd.param"
GETSCOREGOALCMD_PARAM_FIELD.number = 2
GETSCOREGOALCMD_PARAM_FIELD.index = 1
GETSCOREGOALCMD_PARAM_FIELD.label = 1
GETSCOREGOALCMD_PARAM_FIELD.has_default_value = true
GETSCOREGOALCMD_PARAM_FIELD.default_value = 6
GETSCOREGOALCMD_PARAM_FIELD.enum_type = GOALPARAM
GETSCOREGOALCMD_PARAM_FIELD.type = 14
GETSCOREGOALCMD_PARAM_FIELD.cpp_type = 8
GETSCOREGOALCMD_ID_FIELD.name = "id"
GETSCOREGOALCMD_ID_FIELD.full_name = ".Cmd.GetScoreGoalCmd.id"
GETSCOREGOALCMD_ID_FIELD.number = 3
GETSCOREGOALCMD_ID_FIELD.index = 2
GETSCOREGOALCMD_ID_FIELD.label = 1
GETSCOREGOALCMD_ID_FIELD.has_default_value = false
GETSCOREGOALCMD_ID_FIELD.default_value = 0
GETSCOREGOALCMD_ID_FIELD.type = 13
GETSCOREGOALCMD_ID_FIELD.cpp_type = 3
GETSCOREGOALCMD.name = "GetScoreGoalCmd"
GETSCOREGOALCMD.full_name = ".Cmd.GetScoreGoalCmd"
GETSCOREGOALCMD.nested_types = {}
GETSCOREGOALCMD.enum_types = {}
GETSCOREGOALCMD.fields = {
  GETSCOREGOALCMD_CMD_FIELD,
  GETSCOREGOALCMD_PARAM_FIELD,
  GETSCOREGOALCMD_ID_FIELD
}
GETSCOREGOALCMD.is_extendable = false
GETSCOREGOALCMD.extensions = {}
GETSCOREREWARDGOALCMD_CMD_FIELD.name = "cmd"
GETSCOREREWARDGOALCMD_CMD_FIELD.full_name = ".Cmd.GetScoreRewardGoalCmd.cmd"
GETSCOREREWARDGOALCMD_CMD_FIELD.number = 1
GETSCOREREWARDGOALCMD_CMD_FIELD.index = 0
GETSCOREREWARDGOALCMD_CMD_FIELD.label = 1
GETSCOREREWARDGOALCMD_CMD_FIELD.has_default_value = true
GETSCOREREWARDGOALCMD_CMD_FIELD.default_value = 75
GETSCOREREWARDGOALCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
GETSCOREREWARDGOALCMD_CMD_FIELD.type = 14
GETSCOREREWARDGOALCMD_CMD_FIELD.cpp_type = 8
GETSCOREREWARDGOALCMD_PARAM_FIELD.name = "param"
GETSCOREREWARDGOALCMD_PARAM_FIELD.full_name = ".Cmd.GetScoreRewardGoalCmd.param"
GETSCOREREWARDGOALCMD_PARAM_FIELD.number = 2
GETSCOREREWARDGOALCMD_PARAM_FIELD.index = 1
GETSCOREREWARDGOALCMD_PARAM_FIELD.label = 1
GETSCOREREWARDGOALCMD_PARAM_FIELD.has_default_value = true
GETSCOREREWARDGOALCMD_PARAM_FIELD.default_value = 7
GETSCOREREWARDGOALCMD_PARAM_FIELD.enum_type = GOALPARAM
GETSCOREREWARDGOALCMD_PARAM_FIELD.type = 14
GETSCOREREWARDGOALCMD_PARAM_FIELD.cpp_type = 8
GETSCOREREWARDGOALCMD_VERSION_FIELD.name = "version"
GETSCOREREWARDGOALCMD_VERSION_FIELD.full_name = ".Cmd.GetScoreRewardGoalCmd.version"
GETSCOREREWARDGOALCMD_VERSION_FIELD.number = 3
GETSCOREREWARDGOALCMD_VERSION_FIELD.index = 2
GETSCOREREWARDGOALCMD_VERSION_FIELD.label = 1
GETSCOREREWARDGOALCMD_VERSION_FIELD.has_default_value = false
GETSCOREREWARDGOALCMD_VERSION_FIELD.default_value = ""
GETSCOREREWARDGOALCMD_VERSION_FIELD.type = 9
GETSCOREREWARDGOALCMD_VERSION_FIELD.cpp_type = 9
GETSCOREREWARDGOALCMD_VALUE_FIELD.name = "value"
GETSCOREREWARDGOALCMD_VALUE_FIELD.full_name = ".Cmd.GetScoreRewardGoalCmd.value"
GETSCOREREWARDGOALCMD_VALUE_FIELD.number = 4
GETSCOREREWARDGOALCMD_VALUE_FIELD.index = 3
GETSCOREREWARDGOALCMD_VALUE_FIELD.label = 1
GETSCOREREWARDGOALCMD_VALUE_FIELD.has_default_value = false
GETSCOREREWARDGOALCMD_VALUE_FIELD.default_value = 0
GETSCOREREWARDGOALCMD_VALUE_FIELD.type = 13
GETSCOREREWARDGOALCMD_VALUE_FIELD.cpp_type = 3
GETSCOREREWARDGOALCMD.name = "GetScoreRewardGoalCmd"
GETSCOREREWARDGOALCMD.full_name = ".Cmd.GetScoreRewardGoalCmd"
GETSCOREREWARDGOALCMD.nested_types = {}
GETSCOREREWARDGOALCMD.enum_types = {}
GETSCOREREWARDGOALCMD.fields = {
  GETSCOREREWARDGOALCMD_CMD_FIELD,
  GETSCOREREWARDGOALCMD_PARAM_FIELD,
  GETSCOREREWARDGOALCMD_VERSION_FIELD,
  GETSCOREREWARDGOALCMD_VALUE_FIELD
}
GETSCOREREWARDGOALCMD.is_extendable = false
GETSCOREREWARDGOALCMD.extensions = {}
EGOALSTATUS_ACTIVE = 1
EGOALSTATUS_FINISH = 2
EGOALSTATUS_MAX = 3
EGOALSTATUS_MIN = 0
GOALPARAM_GET_GROUP_REWARD = 5
GOALPARAM_GET_ITEM_SCORE = 6
GOALPARAM_GET_SCORE_REWARD = 7
GOALPARAM_QUERY_LIST = 1
GOALPARAM_UPDATE_GROUP = 3
GOALPARAM_UPDATE_ITEM = 2
GOALPARAM_UPDATE_SCORE = 4
GetGroupRewardGoalCmd = protobuf.Message(GETGROUPREWARDGOALCMD)
GetScoreGoalCmd = protobuf.Message(GETSCOREGOALCMD)
GetScoreRewardGoalCmd = protobuf.Message(GETSCOREREWARDGOALCMD)
GoalGroup = protobuf.Message(GOALGROUP)
GoalItem = protobuf.Message(GOALITEM)
GoalScore = protobuf.Message(GOALSCORE)
NewGoalItemUpdateGoalCmd = protobuf.Message(NEWGOALITEMUPDATEGOALCMD)
NewGoalScoreUpdateGoalCmd = protobuf.Message(NEWGOALSCOREUPDATEGOALCMD)
NewGroupUpdateGoalCmd = protobuf.Message(NEWGROUPUPDATEGOALCMD)
QueryGoalListGoalCmd = protobuf.Message(QUERYGOALLISTGOALCMD)
