local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
autoImport("ProtoCommon_pb")
local ProtoCommon_pb = ProtoCommon_pb
module("MessCCmd_pb")
MESSCPARAM = protobuf.EnumDescriptor()
MESSCPARAM_MESSCPARAM_CHOOSE_NEW_PROFESSION_ENUM = protobuf.EnumValueDescriptor()
CHOOSENEWPROFESSIONMESSCCMD = protobuf.Descriptor()
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD = protobuf.FieldDescriptor()
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD = protobuf.FieldDescriptor()
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD = protobuf.FieldDescriptor()
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD = protobuf.FieldDescriptor()
MESSCPARAM_MESSCPARAM_CHOOSE_NEW_PROFESSION_ENUM.name = "MESSCPARAM_CHOOSE_NEW_PROFESSION"
MESSCPARAM_MESSCPARAM_CHOOSE_NEW_PROFESSION_ENUM.index = 0
MESSCPARAM_MESSCPARAM_CHOOSE_NEW_PROFESSION_ENUM.number = 1
MESSCPARAM.name = "MessCParam"
MESSCPARAM.full_name = ".Cmd.MessCParam"
MESSCPARAM.values = {
  MESSCPARAM_MESSCPARAM_CHOOSE_NEW_PROFESSION_ENUM
}
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.name = "cmd"
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.full_name = ".Cmd.ChooseNewProfessionMessCCmd.cmd"
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.number = 1
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.index = 0
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.label = 1
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.has_default_value = true
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.default_value = 83
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.type = 14
CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD.cpp_type = 8
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.name = "param"
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.full_name = ".Cmd.ChooseNewProfessionMessCCmd.param"
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.number = 2
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.index = 1
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.label = 1
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.has_default_value = true
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.default_value = 1
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.enum_type = MESSCPARAM
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.type = 14
CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD.cpp_type = 8
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.name = "bornprofession"
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.full_name = ".Cmd.ChooseNewProfessionMessCCmd.bornprofession"
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.number = 3
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.index = 2
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.label = 1
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.has_default_value = false
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.default_value = nil
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.enum_type = PROTOCOMMON_PB_EPROFESSION
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.type = 14
CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD.cpp_type = 8
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.name = "chooseprofession"
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.full_name = ".Cmd.ChooseNewProfessionMessCCmd.chooseprofession"
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.number = 4
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.index = 3
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.label = 1
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.has_default_value = false
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.default_value = nil
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.enum_type = PROTOCOMMON_PB_EPROFESSION
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.type = 14
CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD.cpp_type = 8
CHOOSENEWPROFESSIONMESSCCMD.name = "ChooseNewProfessionMessCCmd"
CHOOSENEWPROFESSIONMESSCCMD.full_name = ".Cmd.ChooseNewProfessionMessCCmd"
CHOOSENEWPROFESSIONMESSCCMD.nested_types = {}
CHOOSENEWPROFESSIONMESSCCMD.enum_types = {}
CHOOSENEWPROFESSIONMESSCCMD.fields = {
  CHOOSENEWPROFESSIONMESSCCMD_CMD_FIELD,
  CHOOSENEWPROFESSIONMESSCCMD_PARAM_FIELD,
  CHOOSENEWPROFESSIONMESSCCMD_BORNPROFESSION_FIELD,
  CHOOSENEWPROFESSIONMESSCCMD_CHOOSEPROFESSION_FIELD
}
CHOOSENEWPROFESSIONMESSCCMD.is_extendable = false
CHOOSENEWPROFESSIONMESSCCMD.extensions = {}
ChooseNewProfessionMessCCmd = protobuf.Message(CHOOSENEWPROFESSIONMESSCCMD)
MESSCPARAM_CHOOSE_NEW_PROFESSION = 1
